services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_viviendas_transact
    ports:
      - '3310:3306'
    volumes: 
      - ./mysqldata:/mysql/data
    env_file: 
      - ./mysql/variables.env